name: PR comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pr-step
        id: pr-step
        uses: bedlaj/pr-comment-trigger@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: /test %{WORD:param1} %{INT:param2}
      - name: echo
        if: steps.pr-step.outputs.triggered == 'true'
        run: |
          echo 'triggered' ${{steps.pr-step.outputs.triggered}}
          echo 'The param1 is' ${{steps.pr-step.outputs.param1}}
          echo 'The param2 is' ${{steps.pr-step.outputs.param2}}
