name: pr comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
      uses: bedlaj/pr-comment-trigger@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        command: /test
    
